### ISSUE TITLE
Where are the etcetera timezones?

### ISSUE THREAD

**Issue by glasserc** [nilcons/haskell-tzdata#1]
See for example https://www.ietf.org/timezones/data/etcetera.

I see that they're explicitly removed in https://github.com/nilcons/haskell-tzdata/blob/master/build-tzdata.sh. What's the rationale here?

**Comment by klao** [comment]
I am not exactly sure why I left out these Etc time zones. I think, I wanted to avoid the confusion with the pluses and minuses in the names (which cannot be cleanly mapped to haskell identifiers). And also, they are not particularly useful, I think. :)

But, after all, why not. I've merged your changes.

May I ask you what are you using this for? Do you also use the `tz` package? It would be trivial to add a `utcPlusN` helper function there, which just creates a shifted version of UTC... Anyway, I would be interested to hear your suggestions!

**Comment by klao** [comment]
I have updated the package to contain the latest (2015a) data and uploaded it to Hackage. Should be available now!

**Comment by glasserc** [comment]
Wow, thanks for the quick turnaround!

Our use case is probably best summarized with the phrase "backwards compatibility". We have a database of users who have all kinds of bizarre stuff in their timezone field, including "UTC", "Etc/GMT-11" and the extremely puzzling "Central America". The database (and codebase that maintains it) has kind of grown organically over time, I think being originally based on a list of timezones taken from [Rails's ActiveSupport helper library](http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html) with some migration and cleaning done sporadically.

Obviously there's a deeper problem with our data and we need to clean house, but in the meantime we're trying to stand up some helper microservices and to the extent that we can support more of our users without too much corruption of theoretical purity, we'd like to take it :)

Because we're pulling the timezone name from the DB, in actual fact we don't use the Haskell identifiers at all, we always look them up by name.

Hope this helps and please let me know if I can tell you more about how you can make our lives easier ;)

**Comment by klao** [comment]
Oh, I see, I didn't think about people who has to support legacy systems. Makes sense!

> Hope this helps and please let me know if I can tell you more about how you can make our lives easier ;)

Of course, go ahead!  I consider these packages (`tzdata` and `tz`) to be still in experimental state, and the more feedback I can incorporate before they somewhat solidify the better!

**Comment by glasserc** [comment]
Thank you for mentioning the `tz` package -- I myself am still very new to the Haskell ecosystem and don't usually know how everything is intended to fit together. In our actual production code right now, we are using `tzdata` and `timezone-series`, which is somewhat harder than it has to be. I think the intention was to either use `tz` with `tzdata`, or `timezone-olson` with `timezone-series`, but somehow we picked one from each. My co-worker @taphu is the one who prototyped all our timezone stuff and he doesn't seem to have made the choice on purpose. I think we like the idea that `tzdata` encapsulates all the timezone data and has parsed it ahead of time, so that our executable doesn't require timezone files on disk to function correctly.

I spent a few minutes looking at the `tz` package and comparing it to `timezone-series`. Conceptually I like the LocalToUTCResult idea although I don't have a strong intuition about what  its fields represent (and LTUNone isn't documented). (`timezone-series` instead provides `isRedundantLocalTime` and `isValidLocalTime`.) However, we only ever use `localTimeToUTC'`, whose behavior is carefully documented as:

```
When converting from an invalid local time, the local time is
interpreted as if the time change that made it invalid never
happened. When converting from a redundant local time, the latest
possible interpretation is used. Use the functions
isValidLocalTime and isRedundantLocalTime to detect these
conditions.
```

I remember puzzling out the various edge cases a couple months ago and this seemed like the correct behavior to me at the time. I believe `localTimeToUTCTZ` behaves similarly? It isn't documented, and I tried to look at the source but again, because I don't really know what the meanings of the `LTUNone` fields are, I'm not sure.

I guess one other piece of feedback is that TimeZoneSeries seems conceptually cleaner and easier to understand than TZ. I don't think I'd try to construct a TZ by hand, although we have done so with TimeZoneSeries to construct a UTC. (Of course, I see that `tz` defines a `utcTZ`, so presumably we wouldn't have to if we were using `tz`.)

Anyhow that's my feedback. Some of it might simply be the result of being more familiar with TimeZoneSeries than with TZ. I'm going to try doing the conversion in one of our projects and see what my co-workers think. I expect it will allow me to remove code and simplify. I'll let you know if it doesn't :)

**Comment by klao** [comment]
Thanks a lot for your feedback!

Yes, `localTimeToUTCTZ` was modelled explicitly after `localTimeToUTC'` from `timezone-series`, so it should behave exactly the same. I'm not sure why this isn't documented; this is my omission and I'm going to fix it!

I created `tz` for two reasons basically:
1. `timezone-series` is clean, but very inefficient. Of course, this is only important if you are doing a lot of time conversions.
2. I wanted a package that provides the time zone data itself, not just the functions to handle it. I separated this later into `tzdata`, so it could be used by others with for example `timezone-series`. So, I am glad that you guys have found it and used it in the way you described. It means that it was a good idea to do the separation. But, of course, with `tz` it would be easier: you can just use `loadTZFromDB` from `Data.Time.Zones.Read` to get the `TZ` structure given the time zone name.

You can read more about the rationale behind `tz` in this email: http://www.haskell.org/pipermail/haskell-cafe/2014-March/113364.html, or in this reddit thread: http://www.reddit.com/r/haskell/comments/21ujvm/towards_a_better_time_library_announcing_tz/

**Comment by glasserc** [comment]
Well, I still haven't had the chance to try converting. But I do have another request, which is to provide the "UTC" timezone, even if you don't provide any of the other toplevel ones or aliases. My rationale is that it's explicitly listed in the [Wikipedia article about the tz database](http://en.wikipedia.org/wiki/List_of_tz_database_time_zones), with "Etc/UTC" listed as a link to "UTC". Our legacy application isn't so legacy that we have e.g. "Egypt" or "Israel" as timezones in our database, so those aliases are less useful for us, but we definitely do have "UTC" and it feels a little odd to try to say "Well, UTC isn't supported, use Etc/UTC instead". (I guess it's also kind of weird that in our legacy application, a user was permitted to choose UTC as their local timezone, but it could also be a way for them to just say "Don't do any timezone conversion, ever.") What do you think?

**Comment by klao** [comment]
Sure, no problem. I will add it tomorrow!

**Comment by klao** [comment]
Done, I've added everything from the root directory that made sense: 851883d. Now, it should be really complete. :)

I have uploaded it as `0.1.20150129.1` to Hackage, it should be available already.

**Comment by glasserc** [comment]
Thanks! It works great!
