### ISSUE TITLE
Release with 2018c database

### ISSUE THREAD

**Issue by phadej** [nilcons/haskell-tzdata#7]
Recently released: *2018c (Released 2018-01-22)* https://www.iana.org/time-zones

Current release is starting to get old.

**Comment by phadej** [comment]
Is there notes how to update the DB, I can make a PR if there were

**Comment by klao** [comment]
Updated and uploaded to Hackage.

Thanks for pinging me about this!

**Comment by phadej** [comment]
@klao thanks to you!
